server:
  port: 8080

spring:
  application:
    name: XPERT-IN-PRODUCTION
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  time:
    expiration: ${JWT_EXPIRATION_TIME}

email:
  sender:
    gmail: ${EMAIL_SENDER_GMAIL}
    password: ${EMAIL_SENDER_PASSWORD}

verification:
  code:
    expiration: ${VERIFICATION_CODE_EXPIRATION}

user:
  default:
    email: ${USER_DEFAULT_EMAIL}
    username: ${USER_DEFAULT_USERNAME}
    password: ${USER_DEFAULT_PASSWORD}