server:
  port: 8080

spring:
  application:
    name: XPERT-IN-STAGE
  datasource:
    url: jdbc:mysql://localhost:3306/stg_xpert?useSSL=true&serverTimezone=UTC
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  time:
    expiration: ${JWT_EXPIRATION_TIME}

email:
  sender:
    gmail: ${EMAIL_SENDER_GMAIL}
    password: ${EMAIL_SENDER_PASSWORD}

verification:
  code:
    expiration: ${VERIFICATION_CODE_EXPIRATION}

user:
  default:
    email: ${USER_DEFAULT_EMAIL}
    username: ${USER_DEFAULT_USERNAME}
    password: ${USER_DEFAULT_PASSWORD}